####################################################################
#		Pontificia Universidad Javeriana
#
# Autor: Diego Mendoza
# Profesor: J Corredor
# Materia: Sistemas Operativos
# Fichero: Automatizacion de Compilacion
####################################################################

GCC = gcc
FLAGS = -lm -fopenmp

PROGRAMAS = labOMP01 labOMP02 labOMP03 labOMP4 labOMP05 labOMP06

labOMP01:
	$(GCC) $@.c -o $@ $(FLAGS)
labOMP02:
	$(GCC) $@.c -o $@ $(FLAGS)
labOMP03: 
	$(GCC) $@.c -o $@ $(FLAGS)
labOMP04:
	$(GCC) $@.c -o $@ $(FLAGS)
labOMP05:
	$(GCC) $@.c -o $@ $(FLAGS)
labOMP06:
	$(GCC) $@.c -o $@ $(FLAGS)
clean:
	$(RM) $(PROGRAMAS)
