GCC = gcc

PROGRAMAS = lab01_Mendoza lab02_Mendoza lab03_Mendoza

lab01_Mendoza:
	$(GCC) $@.c -o $@
lab02_Mendoza:
	$(GCC) $@.c -o $@
lab03_Mendoza:
	$(GCC) $@-c -o $@
clean: 
     $(RM) $(PROGRAMAS)
