# ====================================================
#	Pontificia Universidad Javeriana
#
# Autor: Diego Mendoza
# Docente: J Corredor
# Materia: Sistemas Operativos
# Tema: Sistemas de ficheros
#
# ====================================================

GCC = gcc
FLAGS = -Wall 
PROGRAMAS = lab_fichero01 lab_fichero02 lab_fichero03

all: $(PROGRAMAS)

lab_fichero01:
	$(GCC) $@.c -o $@ $(FLAGS)
lab_fichero02:
	$(GCC) $@.c -o $@ $(FLAGS)
lab_fichero03:
	$(GCC) $@.c -o $@ $(FLAGS)
clean: 
	$(RM) $(PROGRAMAS)
