##############################################################
# Pontificia Universidad Javeriana
# Autor: Diego Mendoza
# Fecha: 30-10-2025
# Script para automatizar compilación de
# programas para POSIX
# Laboratorio 03
##############################################################

GCC = gcc
FLAGS = -lpthread


PROGRAMAS = labpthread01 labpthread02 labpthread03 labpthread04 labpthread05 labpthread06 labpthread07 labpthread08

labpthread01:
	$(GCC) $@.c -o $@
labpthread02:
	$(GCC) $@.c -o $@
labpthread03: 
	$(GCC) $@.c -o $@
labpthread04:
	$(GCC) $@.c -o $@
labpthread05:
	$(GCC) $@.c -o $@
labpthread06:
	$(GCC) $@.c -o $@
labpthread07:
	$(GCC) $@.c -o $@
labpthread08:
	$(GCC) $@.c -o $@
clean:
	$(RM) $(PROGRAMAS)
