# **************************************************************
# * Nombre: Juan Diego Ariza, Diego Alejandro Mendoza
# * Materia: Sistemas Operativos
# * Profesor: John Corredor, Ph.D.
# * Universidad: Pontificia Universidad Javeriana
# * Fecha: 29/10/2025
# * Descripción: Compilación del programa de procesos y pipes 
# *************************************************************

GCC = gcc
PROGRAMA = taller_procesos

taller_procesos:
	$(GCC) $@.c -o $@

all: $(PROGRAMA)

clean:
	rm -f $(PROGRAMA)
